<script setup lang="ts">
import { useRouter } from 'vue-router'
import AppIcon from '@/components/common/AppIcon.vue'
import AppSelectMenu from '@/components/common/AppSelectMenu.vue'
import AppDatePicker from '@/components/common/AppDatePicker.vue'
import StudentShell from '@/components/layout/StudentShell.vue'
import { useLearningPreparation, preparationSteps as steps, asText, localDate } from '@/composables/useLearningPreparation'
const props = defineProps<{ projectId: string }>()
const router = useRouter()
const { detail, loading, busy, activeStep, error, fieldErrors, stageIndex, target, sourceKnowledgeBaseId, selectedAssets, manualScope, scopeNodes, planTasks, questions, answers, skipReason, skipRequested, resourceConfig, assets, assetsLoading, assetsError, assetCursor, knowledgeBaseOptions, kbLoading, kbError, kbCursor, retryingAssets, drafts, canOpen, selectStep, loadProject, loadAssets, loadKnowledgeBases, isSelected, assetReady, assetState, toggleAsset, retryAsset, confirm, submitDiagnosis, generate, isGenerating, pendingJob, jobError, jobForStep, jobUnresolved, resumeJob, diagnosisState, addNode, removeNode, addTask, removeTask } = useLearningPreparation(props.projectId)
const { state: draftState, status: draftStatus, error: draftError, backupError } = drafts
const options = (labels: string[]) => labels.map(label => ({ value: label, label }))
const foundationOptions = options(['尚未接触', '刚入门', '基础薄弱', '基础一般', '较熟练'])
const priorityOptions = options(['核心', '普通', '了解'])
const difficultyOptions = options(['基础到进阶', '以基础为主', '以考试难度为主'])
const weekdays = [['MONDAY','周一'],['TUESDAY','周二'],['WEDNESDAY','周三'],['THURSDAY','周四'],['FRIDAY','周五'],['SATURDAY','周六'],['SUNDAY','周日']]
const dateValue = (value: string | string[]) => Array.isArray(value) ? value[0] || '' : value
const datesValue = (value: string | string[]) => Array.isArray(value) ? value : value ? [value] : []
function retryJob() { if (jobUnresolved.value && detail.value?.activeJob) resumeJob(detail.value.activeJob.jobId); else if (jobForStep.value) void generate(jobForStep.value) }
</script>

<template>
  <StudentShell compact-on-mobile>
    <div class="setup-page"><div class="setup-container">
      <header class="setup-header">
        <button class="back-button" type="button" aria-label="返回学习项目" :disabled="busy" @click="router.push('/learning')"><AppIcon name="chevron-left" :size="19" /></button>
        <div class="heading"><span class="eyebrow">智能学习 · 准备阶段</span><h1>{{ detail?.name || '学习项目' }}</h1><p>{{ steps[activeStep]?.description }}</p></div>
        <div v-if="detail" class="header-state" role="status" :class="{ 'save-failed': draftState === 'error' || backupError }"><span v-if="busy || draftState === 'saving'" class="dot-spinner" />{{ busy ? '正在确认…' : draftStatus }}</div>
      </header>
      <div v-if="error" class="setup-error" role="alert"><AppIcon name="alert-circle" :size="17" /><span>{{ error }}</span><button v-if="!detail" type="button" @click="loadProject">重新加载</button><button v-else type="button" aria-label="关闭提示" @click="error = ''"><AppIcon name="close" :size="16" /></button></div>
      <div v-if="draftError || backupError" class="setup-error" role="alert"><AppIcon name="alert-circle" :size="17" /><span>{{ draftError || backupError }}<small v-if="!backupError">未保存的修改暂存在此浏览器标签页，重试不会清空输入。</small></span><button type="button" @click="drafts.flush()">重试保存</button></div>
      <div v-if="loading" class="page-loading" role="status"><span class="dot-spinner" />正在加载学习项目…</div>
      <div v-else-if="detail" class="setup-layout">
        <nav class="step-navigation" aria-label="学习准备步骤"><button v-for="(step, index) in steps" :key="step.title" type="button" class="step-nav-item" :class="{ active: activeStep === index, completed: index < stageIndex }" :disabled="!canOpen(index) || busy" :aria-current="activeStep === index ? 'step' : undefined" @click="selectStep(index)"><span class="step-number"><AppIcon v-if="index < stageIndex" name="check" :size="15" /><span v-else>{{ index + 1 }}</span></span><span class="step-copy"><strong>{{ step.title }}</strong><small>{{ step.description }}</small></span><em>{{ index < stageIndex ? '已完成' : canOpen(index) ? '当前' : '未解锁' }}</em></button></nav>
        <main class="step-content"><section class="step-card">
          <header><span class="step-icon"><AppIcon :name="steps[activeStep]?.icon || 'target'" :size="20" /></span><div><h2>{{ steps[activeStep]?.title }}</h2><p>{{ ['先告诉我想达到什么，以及现实中能投入多少时间。','不关联知识库也可以选择资料；只有勾选的文件会用于本项目。','这是基于已确认资料整理的候选范围，可以修改后再确认。','用一轮短诊断了解当前水平；提交前不显示答案和解析。','先调整候选任务，再确认成为当前计划。','决定后续需要准备哪些学习资源。'][activeStep] }}</p></div></header>
          <div v-if="jobError && jobForStep" class="inline-error" role="alert"><span>{{ jobError }}</span><button type="button" @click="retryJob">{{ jobUnresolved ? '查询进度' : '重试' }}</button></div>
          <div v-if="isGenerating" class="generation-state" role="status"><div><span class="dot-spinner" />{{ activeStep === 3 ? '正在准备诊断题目…' : activeStep === 4 ? '正在整理学习计划…' : '正在分析学习范围…' }}</div><p>可以离开此页，回来后继续查看进度。</p><div class="generation-skeleton" aria-hidden="true"><i /><i /><i /></div></div>

          <fieldset v-if="activeStep === 0" class="form-body" :disabled="busy">
            <div class="form-grid">
              <label class="field field-wide"><span>考试或学习目标</span><input v-model="target.examName" placeholder="例如：高数期末考试" :aria-invalid="Boolean(fieldErrors.examName)" @input="delete fieldErrors.examName" /><small v-if="fieldErrors.examName" class="field-error">{{ fieldErrors.examName }}</small></label>
              <div class="field"><span>截止日期 <small>可选</small></span><AppDatePicker :model-value="target.examDate" :min="localDate()" aria-label="截止日期" @update:model-value="target.examDate = dateValue($event); delete fieldErrors.examDate" /><small v-if="fieldErrors.examDate" class="field-error">{{ fieldErrors.examDate }}</small></div>
              <div class="field"><span>不可安排的日期 <small>可多选</small></span><AppDatePicker :model-value="target.blackouts" multiple :min="localDate()" aria-label="不可安排的日期" placeholder="选择不安排学习的日期" @update:model-value="target.blackouts = datesValue($event)" /></div>
              <label class="field"><span>目标分数或水平</span><input v-model="target.targetScore" placeholder="例如：85 分 / 能独立完成项目" /></label>
              <label class="field"><span>每周可用时间 <small>小时</small></span><input v-model.number="target.weeklyHours" type="number" min="0.25" max="168" step="0.25" :aria-invalid="Boolean(fieldErrors.weeklyHours)" @input="delete fieldErrors.weeklyHours" /><small v-if="fieldErrors.weeklyHours" class="field-error">{{ fieldErrors.weeklyHours }}</small></label>
              <div class="field field-wide"><span>通常可以学习的日子</span><div class="day-options"><label v-for="day in weekdays" :key="day[0]" :class="{ selected: target.availableDays.includes(day[0]!) }"><input v-model="target.availableDays" type="checkbox" :value="day[0]" @change="delete fieldErrors.availableDays" /><span>{{ day[1] }}</span></label></div><small v-if="fieldErrors.availableDays" class="field-error">{{ fieldErrors.availableDays }}</small></div>
              <div class="field"><span>自评基础</span><AppSelectMenu v-model="target.foundation" :options="foundationOptions" aria-label="自评基础" /></div>
              <label class="field field-wide"><span>补充要求 <small>可选</small></span><textarea v-model="target.notes" rows="3" placeholder="例如：更重视考试真题，不安排晚于 22 点的任务。" /></label>
            </div>
            <footer><small>修改自动保存；确认后进入下一步。</small><button class="primary-button" type="button" :disabled="Boolean(pendingJob)" @click="confirm('target')">确认目标，选择资料 <AppIcon name="chevron-right" :size="16" /></button></footer>
          </fieldset>

          <fieldset v-else-if="activeStep === 1" class="form-body" :disabled="busy">
            <div class="form-grid"><div class="field"><span>关联知识库 <small>可选</small></span><AppSelectMenu v-model="sourceKnowledgeBaseId" :options="knowledgeBaseOptions" aria-label="关联知识库" /><small v-if="kbLoading">正在加载知识库…</small><div v-if="kbError" class="inline-error"><span>{{ kbError }}</span><button type="button" @click="loadKnowledgeBases()">重试</button></div><button v-if="kbCursor" class="text-button" type="button" :disabled="kbLoading" @click="loadKnowledgeBases(true)">加载更多知识库</button></div></div>
            <div class="source-toolbar"><strong>资料库文件 <small>已选择 {{ selectedAssets.length }} 个</small></strong><button class="text-button" type="button" :disabled="assetsLoading" @click="loadAssets()">刷新列表</button></div>
            <div v-if="assetsError" class="inline-error" role="alert"><span>{{ assetsError }}</span><button type="button" @click="loadAssets()">重新加载</button></div>
            <div class="asset-list"><div v-for="asset in assets" :key="asset.assetId" class="asset-choice" :class="{ selected: isSelected(asset.assetId), unavailable: !assetReady(asset) }"><label><input type="checkbox" :aria-label="asset.name" :checked="isSelected(asset.assetId)" :disabled="!assetReady(asset) && !isSelected(asset.assetId)" @change="toggleAsset(asset)" /><AppIcon name="file" :size="19" /><span class="asset-choice-copy"><strong :title="asset.name">{{ asset.name }}</strong><small>{{ assetState(asset) }}</small></span></label><button v-if="/FAIL/.test(asset.status + asset.version?.status)" class="text-button" type="button" :disabled="retryingAssets.has(asset.assetId)" @click="retryAsset(asset)">{{ retryingAssets.has(asset.assetId) ? '提交中…' : '重新处理' }}</button></div><div v-if="assetsLoading" class="inline-empty" role="status"><span class="dot-spinner" />正在读取资料…</div><div v-else-if="!assets.length && !assetsError" class="inline-empty">资料库中还没有文件，可以先上传后回来选择。</div><button v-if="assetCursor" type="button" class="text-button load-more" :disabled="assetsLoading" @click="loadAssets(true)">加载更多文件</button></div>
            <div v-if="selectedAssets.some(item => !assets.some(asset => asset.assetId === item.assetId))" class="selection-note">已选资料包含尚未加载的文件，选择会保留。<button v-for="item in selectedAssets.filter(item => !assets.some(asset => asset.assetId === item.assetId))" :key="item.assetId" type="button" class="text-button" @click="selectedAssets = selectedAssets.filter(value => value.assetId !== item.assetId)">移除已选文件 {{ item.assetId.slice(-6) }} <AppIcon name="close" :size="12" /></button></div>
            <small v-if="fieldErrors.sources" class="field-error">{{ fieldErrors.sources }}</small>
            <label class="field separated-field"><span>手动范围 <small>没有可用资料时可以填写</small></span><textarea v-model="manualScope" rows="4" placeholder="例如：变量、函数、DOM 事件和异步编程。" /></label>
            <footer><small>只使用勾选文件，不自动加入整个知识库。</small><button class="primary-button" type="button" :disabled="Boolean(pendingJob)" @click="confirm('sources')">确认资料，分析范围 <AppIcon name="chevron-right" :size="16" /></button></footer>
          </fieldset>

          <fieldset v-else-if="activeStep === 2 && !isGenerating" class="form-body" :disabled="busy">
            <div v-if="!scopeNodes.length" class="empty-step"><AppIcon name="sparkle" :size="25" /><strong>还没有学习范围</strong><span>根据已确认资料整理知识点，也可以手动添加。</span><button class="primary-button" type="button" :disabled="Boolean(pendingJob) || jobUnresolved" @click="generate('scope')">开始分析范围</button><button class="text-button" type="button" @click="addNode">手动添加知识点</button></div>
            <div v-else class="editable-list"><div v-for="(node, index) in scopeNodes" :key="node.id" class="editable-row"><span class="row-index">{{ index + 1 }}</span><div class="node-copy"><input v-model="node.title" aria-label="知识点名称" placeholder="知识点名称" /><small :title="node.reason">{{ node.reason || '可补充依据' }}</small></div><AppSelectMenu :model-value="node.priority || '普通'" :options="priorityOptions" aria-label="知识点优先级" @update:model-value="node.priority = $event" /><button class="icon-button" type="button" aria-label="删除知识点" @click="removeNode(index)"><AppIcon name="trash" :size="16" /></button></div><button class="add-row" type="button" @click="addNode"><AppIcon name="plus" :size="15" />添加知识点</button></div>
            <footer v-if="scopeNodes.length"><small>修改自动保存为候选，不影响已确认范围。</small><button class="primary-button" type="button" :disabled="Boolean(pendingJob)" @click="confirm('scope')">确认范围，开始诊断 <AppIcon name="chevron-right" :size="16" /></button></footer>
          </fieldset>

          <fieldset v-else-if="activeStep === 3 && !isGenerating" class="form-body" :disabled="busy">
            <div v-if="diagnosisState === 'skipped'" class="result-box"><AppIcon name="info" :size="18" /><span>已跳过本次诊断：{{ detail.diagnosis.reason }}</span></div>
            <template v-else-if="diagnosisState === 'answering' || diagnosisState === 'submitted'"><div v-if="diagnosisState === 'submitted'" class="result-box"><AppIcon name="check" :size="18" /><span>诊断已提交，可以在学习计划中查看据此安排的任务。</span></div><fieldset class="question-list" :disabled="diagnosisState === 'submitted'"><article v-for="(question, index) in questions" :key="asText(question.id)" class="question-item"><strong>{{ index + 1 }}. {{ question.stem }}</strong><small>{{ question.type === 'short_answer' ? '简答题' : '选择题' }}</small><div v-if="Array.isArray(question.options)" class="options"><label v-for="option in question.options" :key="asText(option)"><input v-model="answers[asText(question.id)]" type="radio" :name="asText(question.id)" :value="asText(option)" /><span>{{ option }}</span></label></div><textarea v-else v-model="answers[asText(question.id)]" rows="3" class="answer-input" placeholder="填写你的答案" /></article></fieldset><footer v-if="diagnosisState === 'answering'"><small>答案自动保存，提交后完成诊断。</small><button class="primary-button" type="button" @click="submitDiagnosis()">提交诊断</button></footer></template>
            <div v-else-if="skipRequested" class="skip-editor"><strong>暂时跳过基础诊断</strong><p>没有诊断结果时，计划会参考自评基础安排。</p><textarea v-model="skipReason" rows="3" maxlength="500" aria-label="跳过原因" placeholder="请填写跳过原因" /><div><button class="text-button" type="button" @click="skipRequested = false">返回诊断</button><button class="primary-button" type="button" :disabled="!skipReason.trim() || Boolean(pendingJob)" @click="submitDiagnosis(true)">确认跳过</button></div></div>
            <div v-else class="empty-step"><AppIcon name="sparkle" :size="25" /><strong>开始一轮基础诊断</strong><span>答题进度自动保存，离开后可以继续。</span><button class="primary-button" type="button" :disabled="Boolean(pendingJob) || jobUnresolved" @click="generate('diagnosis')">生成诊断题目</button><button class="text-button" type="button" :disabled="Boolean(pendingJob) || jobUnresolved" @click="skipRequested = true">暂时跳过诊断</button></div>
          </fieldset>

          <fieldset v-else-if="activeStep === 4 && !isGenerating" class="form-body" :disabled="busy">
            <div v-if="!planTasks.length" class="empty-step"><AppIcon name="sparkle" :size="25" /><strong>还没有计划候选</strong><span>根据目标、范围和诊断结果安排学习任务。</span><button class="primary-button" type="button" :disabled="Boolean(pendingJob) || jobUnresolved" @click="generate('plan')">生成计划候选</button><button class="text-button" type="button" @click="addTask">手动添加任务</button></div>
            <div v-else class="task-list"><article v-for="(task, index) in planTasks" :key="task.id" class="task-row"><span class="row-index">{{ index + 1 }}</span><div class="task-fields"><input v-model="task.title" aria-label="任务名称" placeholder="任务名称" /><div class="task-schedule"><AppDatePicker :model-value="task.date || ''" :min="localDate()" aria-label="任务日期" @update:model-value="task.date = dateValue($event) || null" /><label><input v-model.number="task.durationMinutes" type="number" min="15" max="180" aria-label="预计分钟" /><span>分钟</span></label></div><textarea v-model="task.completionCriteria" rows="2" aria-label="完成标准" placeholder="完成标准" /></div><button class="icon-button" type="button" aria-label="删除任务" @click="removeTask(index)"><AppIcon name="trash" :size="16" /></button></article><button class="add-row" type="button" @click="addTask"><AppIcon name="plus" :size="15" />添加任务</button></div>
            <footer v-if="planTasks.length"><small>修改自动保存为候选，确认后才生效。</small><button class="primary-button" type="button" :disabled="Boolean(pendingJob)" @click="confirm('plan')">确认计划，配置资源 <AppIcon name="chevron-right" :size="16" /></button></footer>
          </fieldset>

          <fieldset v-else-if="activeStep === 5" class="form-body" :disabled="busy">
            <div class="config-options"><label v-for="mode in [{ value: 'rolling', label: '滚动准备', description: '先准备接下来几个有效学习日的资源' }, { value: 'all', label: '一次准备可确定资源', description: '提前准备计划中可以确定的内容' }]" :key="mode.value" class="config-choice" :class="{ selected: resourceConfig.mode === mode.value }"><input v-model="resourceConfig.mode" type="radio" :value="mode.value" /><span><strong>{{ mode.label }}</strong><small>{{ mode.description }}</small></span></label></div>
            <div class="form-grid"><label class="field"><span>滚动准备天数</span><input v-model.number="resourceConfig.effectiveDays" type="number" min="1" max="14" :disabled="resourceConfig.mode !== 'rolling'" /></label><label class="field"><span>练习题数量</span><input v-model.number="resourceConfig.questionCount" type="number" min="0" max="200" /></label><div class="field"><span>题目难度</span><AppSelectMenu v-model="resourceConfig.difficulty" :options="difficultyOptions" aria-label="题目难度" /></div><label class="config-switch"><input v-model="resourceConfig.includeMockExam" type="checkbox" /><span><strong>需要模拟考试</strong><small>资源准备阶段包含一套模拟卷</small></span></label></div>
            <footer><small>资源配置确认后，完成这一轮学习准备。</small><button class="primary-button" type="button" :disabled="Boolean(pendingJob)" @click="confirm('resources')">确认配置，完成准备 <AppIcon name="check" :size="16" /></button></footer><div v-if="detail.stage === 'READY'" class="result-box"><AppIcon name="check" :size="19" /><span>学习准备已完成：计划和资源配置均已确认，资源待准备。</span></div>
          </fieldset>
        </section></main>
      </div>
    </div></div>
  </StudentShell>
</template>

<style scoped>
.setup-page,.setup-page :deep(*){box-sizing:border-box}.setup-page{min-height:100%;padding:26px 28px 70px;background:var(--ui-page-canvas-bg);color:var(--color-text);font-size:14px}.setup-container{width:100%;max-width:1140px;margin:0 auto;container-type:inline-size;container-name:learning-setup}.setup-header{display:flex;gap:14px;align-items:center;min-height:76px}.heading{min-width:0;flex:1}.eyebrow{font-size:12px;font-weight:600;color:var(--color-text-muted)}h1,h2,p{margin:0}h1{font-size:25px;margin:5px 0;overflow-wrap:anywhere}.heading p{font-size:13px;color:var(--color-text-muted)}.header-state{max-width:270px;line-height:1.5;font-size:12px;color:var(--color-text-muted)}.save-failed{color:var(--color-danger)}button,input,textarea{font:inherit}button{cursor:pointer}button:disabled{opacity:.5;cursor:not-allowed}button:focus-visible{outline:2px solid var(--color-text-muted);outline-offset:2px}.back-button,.icon-button{display:grid;place-items:center;flex-shrink:0;color:var(--color-text-muted);border:0;background:transparent;border-radius:8px;width:32px;height:32px}.back-button{width:40px;height:40px;border:1px solid var(--color-border);background:var(--color-surface)}.icon-button:hover,.back-button:hover{background:var(--color-hover);color:var(--color-text)}
.setup-error,.inline-error{display:flex;align-items:center;gap:10px;padding:12px 14px;margin-top:14px;border:1px solid color-mix(in srgb,var(--color-danger) 25%,var(--color-border));border-radius:9px;background:color-mix(in srgb,var(--color-danger) 5%,var(--color-surface));color:var(--color-danger);max-width:100%;line-height:1.5}.setup-error>span,.inline-error>span{flex:1;min-width:0;overflow-wrap:anywhere}.setup-error>svg{flex-shrink:0}.setup-error small{display:block}.setup-error button,.inline-error button{flex-shrink:0;border:0;background:transparent;color:inherit;padding:4px;white-space:nowrap}.page-loading,.inline-empty{padding:30px 12px;color:var(--color-text-muted);text-align:center}
.setup-layout{display:grid;grid-template-columns:288px minmax(0,1fr);gap:22px;align-items:start;margin-top:22px}.step-navigation{position:sticky;top:18px;display:grid;gap:6px;min-width:0;padding:12px;border:1px solid var(--color-border);border-radius:13px;background:var(--color-surface);box-shadow:var(--shadow-sm)}.step-nav-item{min-height:76px;display:grid;grid-template-columns:28px minmax(0,1fr) auto;align-items:center;gap:9px;padding:11px 10px;border:1px solid transparent;border-radius:10px;background:transparent;color:var(--color-text-muted);text-align:left}.step-nav-item.active{background:var(--color-hover);color:var(--color-text);border-color:var(--color-border)}.step-nav-item:hover:not(:disabled){background:var(--color-hover)}.step-number{width:28px;height:28px;display:grid;place-items:center;border:1px solid var(--color-border);border-radius:50%;font-size:12px}.completed .step-number{background:var(--color-primary);border-color:var(--color-primary);color:var(--color-on-primary)}.step-copy{display:grid;gap:4px;min-width:0}.step-copy small{font-size:12px;line-height:1.5;overflow-wrap:anywhere}.step-copy strong{font-weight:600}.step-nav-item em{font-style:normal;font-size:10px;white-space:nowrap}.step-content{min-width:0}.step-card{padding:24px;border:1px solid var(--color-border);border-radius:13px;background:var(--color-surface);box-shadow:var(--shadow-sm);min-width:0}.step-card>header{display:flex;align-items:flex-start;gap:12px;border-bottom:1px solid var(--color-border);padding-bottom:20px}.step-icon{width:38px;height:38px;flex-shrink:0;display:grid;place-items:center;border-radius:10px;background:var(--color-hover)}h2{font-size:20px}.step-card header p{color:var(--color-text-muted);font-size:13px;line-height:1.6;margin-top:5px}.form-body{border:0;padding:0;margin:0;min-width:0;width:100%;max-width:none}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px 22px;margin-top:24px}.field{display:flex;flex-direction:column;gap:8px;min-width:0}.field>span{font-weight:600}.field small{font-size:12px;color:var(--color-text-muted);font-weight:400}.field-wide{grid-column:1/-1}.separated-field{margin-top:22px}.field input:not([type=checkbox]):not([type=radio]),textarea,.node-copy input,.task-fields input{width:100%;min-width:0;border:1px solid var(--color-border);border-radius:9px;background:var(--color-surface);color:var(--color-text);font-weight:400;outline:none}.field input:not([type=checkbox]):not([type=radio]),.node-copy input,.task-fields input{height:40px;padding:0 12px}textarea{resize:vertical;padding:10px 12px;line-height:1.6;min-height:84px}input::placeholder,textarea::placeholder{color:var(--color-text-muted);font-weight:400}input:not([type=checkbox]):not([type=radio]),textarea,:deep(.app-select-menu__trigger),:deep(.date-trigger){transition:border-color .16s ease,box-shadow .16s ease}
input:not([type=checkbox]):not([type=radio]):focus,textarea:focus,
:deep(.app-select-menu__trigger:focus),:deep(.app-select-menu__trigger[aria-expanded=true]),
:deep(.date-trigger:focus),:deep(.date-trigger[aria-expanded=true]){
  outline:0;border-color:color-mix(in srgb,var(--color-text) 70%,var(--color-border));
  box-shadow:0 0 0 3px color-mix(in srgb,var(--color-text) 8%,transparent),0 2px 5px color-mix(in srgb,var(--color-text) 4%,transparent)
}
.day-options label:focus-within,.asset-choice:focus-within,.config-choice:focus-within{outline:0;border-color:var(--color-text-muted);box-shadow:0 0 0 3px color-mix(in srgb,var(--color-text) 8%,transparent)}
input[aria-invalid=true]{border-color:var(--color-danger)}.field-error,.field .field-error{display:block;color:var(--color-danger);font-size:12px;line-height:1.5}.field :deep(.app-select-menu__trigger){font-size:14px;font-weight:400;background:var(--color-surface);border-radius:9px}input[type=checkbox],input[type=radio]{width:15px;height:15px;margin:0;flex-shrink:0;accent-color:var(--color-primary)}.day-options{display:flex;flex-wrap:wrap;gap:7px}.day-options label{height:36px;display:flex;align-items:center;gap:6px;padding:0 10px;border:1px solid var(--color-border);border-radius:8px;font-size:12px;white-space:nowrap;cursor:pointer}.day-options label.selected{background:var(--color-hover);border-color:var(--color-text-muted)}footer{display:flex;align-items:center;justify-content:flex-end;flex-wrap:wrap;gap:12px;border-top:1px solid var(--color-border);margin-top:26px;padding-top:18px}footer>small{flex:1;min-width:150px;color:var(--color-text-muted);font-size:12px;line-height:1.5}.primary-button{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-height:39px;max-width:100%;padding:8px 14px;border:1px solid var(--color-primary);border-radius:9px;background:var(--color-primary);color:var(--color-on-primary);font-weight:600;font-size:13px}.text-button,.add-row{display:inline-flex;align-items:center;gap:5px;border:0;background:transparent;color:var(--color-text-muted);font-size:13px;padding:5px 0}.text-button:hover,.add-row:hover{color:var(--color-text)}
.source-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:24px}.source-toolbar small{font-weight:400;color:var(--color-text-muted);margin-left:6px}.asset-list{display:grid;gap:8px;max-height:330px;overflow-y:auto;overflow-x:hidden;margin-top:10px;padding:4px 14px 4px 4px;scrollbar-gutter:stable;scrollbar-width:thin;scroll-padding-block:4px}.asset-choice{display:flex;align-items:center;gap:8px;padding:11px 12px;min-width:0;border:1px solid var(--color-border);border-radius:9px}.asset-choice.selected{background:var(--color-hover);border-color:var(--color-text-muted)}.asset-choice>label{display:flex;align-items:center;gap:12px;flex:1;min-width:0;cursor:pointer}.asset-choice svg{flex-shrink:0}.asset-choice.unavailable{color:var(--color-text-muted)}.asset-choice-copy{display:grid;gap:4px;min-width:0;flex:1}.asset-choice strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:500}.asset-choice small{color:var(--color-text-muted);font-size:12px}.load-more{justify-self:center}.selection-note{display:flex;align-items:center;gap:6px;flex-wrap:wrap;font-size:12px;color:var(--color-text-muted);margin-top:8px}
.empty-step{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;min-height:280px;text-align:center;color:var(--color-text-muted);line-height:1.6}.empty-step strong{color:var(--color-text)}.editable-list,.task-list{display:grid;gap:12px;margin-top:22px}.editable-row{display:grid;grid-template-columns:22px minmax(0,1fr) 94px 28px;align-items:start;gap:8px}.row-index{color:var(--color-text-muted);font-size:12px;line-height:40px;text-align:center}.node-copy{display:grid;gap:5px;min-width:0}.node-copy small{color:var(--color-text-muted);font-size:11px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.editable-row .icon-button{margin-top:4px}.add-row{justify-self:start}.question-list{display:grid;gap:14px;margin:22px 0 0;padding:0;border:0;min-width:0}.question-item{padding:16px;border:1px solid var(--color-border);border-radius:10px;line-height:1.6;overflow-wrap:anywhere}.question-item>small{display:block;color:var(--color-text-muted);margin-top:5px}.options{display:grid;gap:10px;margin-top:12px}.options label{display:flex;gap:9px;align-items:flex-start}.options input{margin-top:4px}.answer-input{margin-top:12px}.result-box{display:flex;align-items:flex-start;gap:10px;line-height:1.6;margin-top:22px;padding:15px;border:1px solid var(--color-border);border-radius:9px;background:var(--color-hover);color:var(--color-text-muted)}.result-box svg{flex-shrink:0;margin-top:2px}.skip-editor{display:grid;gap:12px;margin-top:22px}.skip-editor p{color:var(--color-text-muted);font-size:13px}.skip-editor>div{display:flex;gap:15px;justify-content:flex-end}.task-row{display:grid;grid-template-columns:20px minmax(0,1fr) 28px;gap:8px;border:1px solid var(--color-border);border-radius:10px;padding:13px}.task-fields{display:grid;gap:10px;min-width:0}.task-schedule{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.task-schedule>label{position:relative;display:flex;align-items:center;min-width:0;font-size:12px;color:var(--color-text-muted)}
.task-schedule>label input{padding-right:52px}
.task-schedule>label>span{position:absolute;right:12px;white-space:nowrap;pointer-events:none}
.task-schedule>label input::-webkit-inner-spin-button,.task-schedule>label input::-webkit-outer-spin-button{-webkit-appearance:none;margin:0}
.task-schedule>label input[type=number]{appearance:textfield;-moz-appearance:textfield}
.task-fields textarea{min-height:70px}.config-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:24px}.config-choice{display:flex;align-items:flex-start;gap:8px;padding:14px;border:1px solid var(--color-border);border-radius:10px;cursor:pointer}.config-choice.selected{background:var(--color-hover);border-color:var(--color-text-muted)}.config-choice span,.config-switch span{display:grid;gap:6px}.config-choice input{margin-top:2px}.config-choice small,.config-switch small{font-size:12px;color:var(--color-text-muted);line-height:1.5}.config-switch{display:flex;align-items:center;gap:10px}.dot-spinner{display:inline-block;width:14px;height:14px;margin-right:7px;border:2px solid var(--color-border);border-top-color:var(--color-text-muted);border-radius:50%;vertical-align:-2px;animation:spin .8s linear infinite}.generation-state{padding:32px 0 12px;color:var(--color-text-muted);width:100%}.generation-state p{font-size:12px;margin-top:10px}.generation-skeleton{display:grid;gap:14px;padding:25px 0}.generation-skeleton i{height:15px;background:var(--color-hover);border-radius:6px;animation:pulse 1.5s ease infinite}.generation-skeleton i:nth-child(2){width:86%}.generation-skeleton i:nth-child(3){width:64%}@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{50%{opacity:.4}}@media(prefers-reduced-motion:reduce){.dot-spinner,.generation-skeleton i{animation:none}}
@media(max-width:1080px){.setup-page{padding:22px 20px 65px}}
@media(max-width:520px){.setup-page{padding:16px 12px 50px}}
@container learning-setup (max-width:920px){
  .setup-layout{grid-template-columns:248px minmax(0,1fr);gap:16px}
  .step-navigation{padding:10px}
  .step-nav-item em{display:none}
  .step-nav-item{grid-template-columns:28px minmax(0,1fr)}
  .step-card{padding:20px}
  .form-grid{gap:18px 16px}
  .header-state{max-width:200px}
}
@container learning-setup (max-width:720px){
  .setup-layout{grid-template-columns:minmax(0,1fr)}
  .step-navigation{display:flex;overflow-x:auto;position:static;padding:10px;scrollbar-width:thin}
  .step-nav-item{flex:0 0 148px;min-height:54px}
  .step-copy small{display:none}
  .header-state{max-width:150px}
}
@container learning-setup (max-width:480px){
  .setup-header{flex-wrap:wrap;gap:10px}
  .header-state{flex-basis:100%;max-width:none;margin-left:50px}
  h1{font-size:22px}
  .step-card{padding:16px}
  .form-grid,.config-options{grid-template-columns:minmax(0,1fr)}
  .field-wide{grid-column:auto}
  .editable-row{grid-template-columns:18px minmax(0,1fr) 82px 24px;gap:5px}
  .task-row{grid-template-columns:18px minmax(0,1fr) 24px;padding:10px;gap:4px}
  .task-schedule{grid-template-columns:minmax(0,1fr)}
  footer>small{flex-basis:100%}
  .source-toolbar{flex-wrap:wrap}
  .day-options{gap:6px}
  .asset-list{padding-right:12px}
}
</style>
